import { OConfigureServiceArgs, QuickFilterFunction } from "ontimize-web-ngx";

export type ODataViewMode = 'table' | 'grid' | 'list';

export interface ODataViewConfig {
  defaultView?: ODataViewMode;
  attr?: string;
  columns?: string;
  configureServiceArgs?: OConfigureServiceArgs;
  entity?: string;
  keys?: string;
  pageable?: 'no' | 'false' | 'yes' | 'true';
  paginatedQueryMethod?: string;
  parentKeys?: string;
  queryFallbackFunction?: Function;
  queryMethod?: string;
  queryOnBind?: 'no' | 'false' | 'yes' | 'true';
  queryOnInit?: 'no' | 'false' | 'yes' | 'true';
  queryRows?: number;
  queryWithNullParentKeys?: 'no' | 'false' | 'yes' | 'true';
  service?: string;
  serviceType?: string;
  staticData?: any[];
  storeState?: 'no' | 'false' | 'yes' | 'true';
  controls?: string;
  detailFormRoute?: string;
  detailMode?: string;
  enabled?: string;
  pageSizeOptions?: string;
  paginationControls?: string;
  quickFilter?: string;
  quickFilterPlaceholder?: string;
  recursiveDetail?: string;
  title?: string;
  visible?: string;
  tableCfg?: {
    deleteMethod?: string;
    insertMethod?: string;
    updateMethod?: string;
    detailButtonInRow?: string;
    detailButtonInRowIcon?: string;
    editButtonInRow?: string;
    editButtonInRowIcon?: string;
    editFormRoute?: string;
    filterCaseSensitive?: string;
    insertButton?: string;
    insertFormRoute?: string;
    recursiveEdit?: string;
    recursiveInsert?: string;
    rowHeight?: string;
    autoAdjust?: 'no' | 'false' | 'yes' | 'true';
    autoAlignTitles?: 'no' | 'false' | 'yes' | 'true';
    collapseGroupedColumns?: 'no' | 'false' | 'yes' | 'true';
    columnsVisibilityButton?: 'no' | 'false' | 'yes' | 'true';
    defaultVisibleColumns?: string;
    deleteButton?: 'no' | 'false' | 'yes' | 'true';
    detailMode?: 'none' | 'click' | 'dblclick';
    disableSelectionFunction?: (item: any) => boolean;
    editionMode?: 'none' | 'click' | 'dblclick';
    enabled?: 'no' | 'false' | 'yes' | 'true';
    exportButton?: 'no' | 'false' | 'yes' | 'true';
    exportServiceType?: string;
    filterColumnActiveByDefault?: 'no' | 'false' | 'yes' | 'true';
    fixedHeader?: 'no' | 'false' | 'yes' | 'true';
    groupable?: 'no' | 'false' | 'yes' | 'true';
    groupedColumns?: string;
    horizontalScroll?: 'no' | 'false' | 'yes' | 'true';
    keepSelectedItems?: 'no' | 'false' | 'yes' | 'true';
    multipleSort?: 'no' | 'false' | 'yes' | 'true';
    nonHidableColumns?: string;
    orderable?: 'no' | 'false' | 'yes' | 'true';
    paginationControls?: 'no' | 'false' | 'yes' | 'true';
    quickFilterFunction?: QuickFilterFunction;
    refreshButton?: 'no' | 'false' | 'yes' | 'true';
    resizable?: 'no' | 'false' | 'yes' | 'true';
    rowClass?: (rowData: any, rowIndex: number) => string | string[];
    selectAllCheckbox?: 'no' | 'false' | 'yes' | 'true';
    selectAllCheckboxVisible?: 'no' | 'false' | 'yes' | 'true';
    selectionMode?: 'none' | 'single' | 'multiple';
    showButtonsText?: 'no' | 'false' | 'yes' | 'true';
    showConfigurationOption?: 'no' | 'false' | 'yes' | 'true';
    showExpandableIconFunction?: Function;
    showFilterOption?: 'no' | 'false' | 'yes' | 'true';
    showPaginatorFirstLastButtons?: 'no' | 'false' | 'yes' | 'true';
    showReportOnDemandOption?: 'no' | 'false' | 'yes' | 'true';
    showResetWidthOption?: 'no' | 'false' | 'yes' | 'true';
    showTitle?: 'no' | 'false' | 'yes' | 'true';
    sortColumns?: string;
    virtualScroll?: 'no' | 'false' | 'yes' | 'true';
    visibleColumns?: string;
    visibleExportDialogButtons?: string;
  };
  gridCfg?: {
    cols?: number;
    fixedHeader?: 'no' | 'false' | 'yes' | 'true';
    gridItemHeight?: string | number;
    gutterSize?: string;
    insertButton?: 'no' | 'false' | 'yes' | 'true';
    insertButtonFloatable?: 'no' | 'false' | 'yes' | 'true';
    insertButtonPosition?: 'botton' | 'top';
    orderable?: 'no' | 'false' | 'yes' | 'true';
    pageSizeOptions?: any[];
    paginationControls?: 'no' | 'false' | 'yes' | 'true';
    quickFilterColumns?: string;
    refreshButton?: 'no' | 'false' | 'yes' | 'true';
    showButtonsText?: 'no' | 'false' | 'yes' | 'true';
    showFooter?: 'no' | 'false' | 'yes' | 'true';
    showPageSize?: 'no' | 'false' | 'yes' | 'true';
    sortColumn?: string;
    sortableColumns?: string;
  };
  listCfg?: {
    deleteMethod?: string;
    insertMethod?: string;
    updateMethod?: string;
    detailButtonInRow?: string;
    detailButtonInRowIcon?: string;
    editButtonInRow?: string;
    editButtonInRowIcon?: string;
    editFormRoute?: string;
    insertButton?: string;
    insertFormRoute?: string;
    quickFilterAppearance?: string;
    recursiveEdit?: string;
    recursiveInsert?: string;
    rowHeight?: string;
    deleteButton?: 'no' | 'false' | 'yes' | 'true';
    insertButtonFloatable?: 'no' | 'false' | 'yes' | 'true';
    insertButtonPosition?: 'botton' | 'top';
    keysSqlTypes?: string;
    paginationControls?: 'no' | 'false' | 'yes' | 'true';
    quickFilterColumns?: string;
    refreshButton?: 'no' | 'false' | 'yes' | 'true';
    selectable?: 'no' | 'false' | 'yes' | 'true';
    showButtonsText?: 'no' | 'false' | 'yes' | 'true';
    sortColumns?: string;
  }
}