export interface GridConfig {
  controls?: 'no' | 'false' | 'yes' | 'true';
  detailFormRoute?: 'no' | 'false' | 'yes' | 'true';
  detailMode?: 'none' | 'click' | 'dbclick';
  enabled?: 'no' | 'false' | 'yes' | 'true';
  quickFilter?: 'no' | 'false' | 'yes' | 'true';
  quickFilterPlaceholder?: string;
  quickFilterAppearance?: 'legacy' | 'standard' | 'fill' | 'outline';
  recursiveDetail?: 'no' | 'false' | 'yes' | 'true';
  title?: string;
  visible?: 'no' | 'false' | 'yes' | 'true';
  cols?: number;
  fixedHeader?: 'no' | 'false' | 'yes' | 'true';
  gridItemHeight?: string | number;
  gutterSize?: string;
  insertButton?: 'no' | 'false' | 'yes' | 'true';
  insertButtonFloatable?: 'no' | 'false' | 'yes' | 'true';
  insertButtonPosition?: 'botton' | 'top';
  orderable?: 'no' | 'false' | 'yes' | 'true';
  pageSizeOptions?: any[];
  paginationControls?: 'no' | 'false' | 'yes' | 'true';
  quickFilterColumns?: string;
  refreshButton?: 'no' | 'false' | 'yes' | 'true';
  showButtonsText?: 'no' | 'false' | 'yes' | 'true';
  showFooter?: 'no' | 'false' | 'yes' | 'true';
  showPageSize?: 'no' | 'false' | 'yes' | 'true';
  sortColumn?: string;
  sortableColumns?: string;
};

