import { QuickFilterFunction } from "ontimize-web-ngx";
import { CustomBoolean } from "../types";

export interface TableConfig {
  controls?: CustomBoolean;
  detailFormRoute?: string;
  pageSizeOptions?: any[];
  quickFilter?: CustomBoolean;
  recursiveDetail?: CustomBoolean;
  title?: string;
  visible?: CustomBoolean;
  detailButtonInRow?: CustomBoolean;
  detailButtonInRowIcon?: string;
  editButtonInRow?: CustomBoolean;
  editButtonInRowIcon?: string;
  editFormRoute?: string;
  filterCaseSensitive?: CustomBoolean;
  insertFormRoute?: string;
  recursiveEdit?: CustomBoolean;
  recursiveInsert?: CustomBoolean;
  rowHeight?: 'small' | 'medium' | 'large';
  autoAdjust?: CustomBoolean;
  autoAlignTitles?: CustomBoolean;
  collapseGroupedColumns?: CustomBoolean;
  columnsVisibilityButton?: CustomBoolean;
  defaultVisibleColumns?: string;
  deleteButton?: CustomBoolean;
  detailMode?: 'none' | 'click' | 'dblclick';
  disableSelectionFunction?: (item: any) => boolean;
  editionMode?: 'none' | 'click' | 'dblclick';
  enabled?: CustomBoolean;
  exportButton?: CustomBoolean;
  exportServiceType?: string;
  filterColumnActiveByDefault?: CustomBoolean;
  fixedHeader?: CustomBoolean;
  groupable?: CustomBoolean;
  groupedColumns?: string;
  horizontalScroll?: CustomBoolean;
  keepSelectedItems?: CustomBoolean;
  multipleSort?: CustomBoolean;
  nonHidableColumns?: string;
  orderable?: CustomBoolean;
  paginationControls?: CustomBoolean;
  quickFilterFunction?: QuickFilterFunction;
  resizable?: CustomBoolean;
  rowClass?: (rowData: any, rowIndex: number) => string | string[];
  selectAllCheckbox?: CustomBoolean;
  selectAllCheckboxVisible?: CustomBoolean;
  selectionMode?: 'none' | 'single' | 'multiple';
  showConfigurationOption?: CustomBoolean;
  showExpandableIconFunction?: Function;
  showFilterOption?: CustomBoolean;
  showPaginatorFirstLastButtons?: CustomBoolean;
  showReportOnDemandOption?: CustomBoolean;
  showResetWidthOption?: CustomBoolean;
  showTitle?: CustomBoolean;
  sortColumns?: string;
  virtualScroll?: CustomBoolean;
  visibleColumns?: string;
  visibleExportDialogButtons?: string;
  selectionOnRowClick?: CustomBoolean;
};
